/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_breaker_token1 = 1,
  aux_sym_instruction_token1 = 2,
  sym_unordered = 3,
  sym_one_of = 4,
  sym_and_then = 5,
  sym_optional = 6,
  sym_clipbo = 7,
  sym_clipboard_string = 8,
  sym_comment = 9,
  sym_source_file = 10,
  sym_breaker = 11,
  sym_instruction_line = 12,
  sym_instruction = 13,
  sym_marker = 14,
  sym_clipboard_line = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_instruction_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_breaker_token1] = "breaker_token1",
  [aux_sym_instruction_token1] = "instruction_token1",
  [sym_unordered] = "unordered",
  [sym_one_of] = "one_of",
  [sym_and_then] = "and_then",
  [sym_optional] = "optional",
  [sym_clipbo] = "clipbo",
  [sym_clipboard_string] = "clipboard_string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_breaker] = "breaker",
  [sym_instruction_line] = "instruction_line",
  [sym_instruction] = "instruction",
  [sym_marker] = "marker",
  [sym_clipboard_line] = "clipboard_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_breaker_token1] = aux_sym_breaker_token1,
  [aux_sym_instruction_token1] = aux_sym_instruction_token1,
  [sym_unordered] = sym_unordered,
  [sym_one_of] = sym_one_of,
  [sym_and_then] = sym_and_then,
  [sym_optional] = sym_optional,
  [sym_clipbo] = sym_clipbo,
  [sym_clipboard_string] = sym_clipboard_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_breaker] = sym_breaker,
  [sym_instruction_line] = sym_instruction_line,
  [sym_instruction] = sym_instruction,
  [sym_marker] = sym_marker,
  [sym_clipboard_line] = sym_clipboard_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_breaker_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_unordered] = {
    .visible = true,
    .named = true,
  },
  [sym_one_of] = {
    .visible = true,
    .named = true,
  },
  [sym_and_then] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_clipbo] = {
    .visible = true,
    .named = true,
  },
  [sym_clipboard_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_breaker] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction_line] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_clipboard_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') SKIP(6);
      if (lookahead == '&') ADVANCE(12);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(1);
      if (lookahead == '?') ADVANCE(15);
      if (lookahead == '|') ADVANCE(13);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(19);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') SKIP(6);
      if (lookahead == '&') ADVANCE(12);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '?') ADVANCE(15);
      if (lookahead == '|') ADVANCE(13);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_breaker_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_instruction_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_instruction_token1);
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_instruction_token1);
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_unordered);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_one_of);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_and_then);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_optional);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_clipbo);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_clipboard_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_clipboard_string);
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_breaker_token1] = ACTIONS(1),
    [sym_unordered] = ACTIONS(1),
    [sym_one_of] = ACTIONS(1),
    [sym_and_then] = ACTIONS(1),
    [sym_optional] = ACTIONS(1),
    [sym_clipbo] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(12),
    [sym_breaker] = STATE(2),
    [sym_instruction_line] = STATE(2),
    [sym_marker] = STATE(7),
    [sym_clipboard_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_breaker_token1] = ACTIONS(7),
    [sym_unordered] = ACTIONS(9),
    [sym_one_of] = ACTIONS(9),
    [sym_and_then] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [sym_clipbo] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_breaker] = STATE(3),
    [sym_instruction_line] = STATE(3),
    [sym_marker] = STATE(7),
    [sym_clipboard_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym_breaker_token1] = ACTIONS(7),
    [sym_unordered] = ACTIONS(9),
    [sym_one_of] = ACTIONS(9),
    [sym_and_then] = ACTIONS(9),
    [sym_optional] = ACTIONS(9),
    [sym_clipbo] = ACTIONS(11),
    [sym_comment] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_breaker] = STATE(3),
    [sym_instruction_line] = STATE(3),
    [sym_marker] = STATE(7),
    [sym_clipboard_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_breaker_token1] = ACTIONS(21),
    [sym_unordered] = ACTIONS(24),
    [sym_one_of] = ACTIONS(24),
    [sym_and_then] = ACTIONS(24),
    [sym_optional] = ACTIONS(24),
    [sym_clipbo] = ACTIONS(27),
    [sym_comment] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(33), 8,
      ts_builtin_sym_end,
      aux_sym_breaker_token1,
      sym_unordered,
      sym_one_of,
      sym_and_then,
      sym_optional,
      sym_clipbo,
      sym_comment,
  [11] = 1,
    ACTIONS(35), 8,
      ts_builtin_sym_end,
      aux_sym_breaker_token1,
      sym_unordered,
      sym_one_of,
      sym_and_then,
      sym_optional,
      sym_clipbo,
      sym_comment,
  [22] = 1,
    ACTIONS(37), 8,
      ts_builtin_sym_end,
      aux_sym_breaker_token1,
      sym_unordered,
      sym_one_of,
      sym_and_then,
      sym_optional,
      sym_clipbo,
      sym_comment,
  [33] = 4,
    ACTIONS(39), 1,
      aux_sym_instruction_token1,
    ACTIONS(41), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_instruction_repeat1,
    STATE(14), 1,
      sym_instruction,
  [46] = 4,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym_breaker_token1,
    ACTIONS(45), 1,
      aux_sym_instruction_token1,
    STATE(9), 1,
      aux_sym_instruction_repeat1,
  [59] = 4,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(47), 1,
      aux_sym_breaker_token1,
    ACTIONS(49), 1,
      aux_sym_instruction_token1,
    STATE(9), 1,
      aux_sym_instruction_repeat1,
  [72] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(52), 1,
      aux_sym_instruction_token1,
  [79] = 2,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(54), 1,
      sym_clipboard_string,
  [86] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
  [93] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_breaker_token1,
  [100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      aux_sym_breaker_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 11,
  [SMALL_STATE(6)] = 22,
  [SMALL_STATE(7)] = 33,
  [SMALL_STATE(8)] = 46,
  [SMALL_STATE(9)] = 59,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 79,
  [SMALL_STATE(12)] = 86,
  [SMALL_STATE(13)] = 93,
  [SMALL_STATE(14)] = 100,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_breaker, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clipboard_line, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_line, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_marker, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [56] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_oats(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
